function Hd = designDifferentiator(N)
% Hd = designDifferentiator(N)
%
% M-File generated by MATLAB(R) 7.10 and the Signal Processing Toolbox 6.13.
%
% Generated on: 16-Mar-2015 13:56:19
%
% FIR least-squares Differentiator filter designed using the FIRLS
% function.

% All frequency values are normalized to 1.
if nargin<1
    N = 50;              % Order
end
F = [0 0.5 0.55 1];  % Frequency Vector
A = [0 1 0 0];       % Amplitude Vector
W = [1 1];           % Weight Vector

% Calculate the coefficients using the FIRLS function.
b  = firls(N, F, A, W, 'differentiator');
Hd = dfilt.dffir(b);

% [EOF]
