function Hd = makeDifferentiator
% Hd = makeDifferentiator
% Returns a discrete-time filter object.
%
% Brian Goodwin 2014-02-23
%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
%
% Generated on: 23-Feb-2015 16:49:25
%

% Equiripple Differentiator filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N = 40;              % Order
F = [0 0.5 0.55 1];  % Frequency Vector
A = [0 1 0 0];       % Amplitude Vector
W = [1 1];           % Weight Vector

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, F, A, W, 'differentiator');
Hd = dfilt.dffir(b);

% [EOF]
